### ISSUE TITLE
Download links down

### ISSUE THREAD

**Issue by Noixas** [coosto/dutch-word-embeddings#1]
The download links for all the embeddings are not working.
![image](https://user-images.githubusercontent.com/23318473/82595887-ac8cb380-9ba6-11ea-82d9-1893df431735.png)

**Comment by severun** [comment]
Hello @Noixas,

I just double-checked the scripts and the links, but everything seems to work.
The screenshot you provided shows a link to clips.uantwerpen.be but this URL is not used within this repo. Are you sure that you are using the Correct GitHub repository? Could you please explain to me what steps you took to download the model?

You can also try to directly download it from GitHub using the [releases page](https://github.com/coosto/dutch-word-embeddings/releases).

**Comment by Noixas** [comment]
OMG I'm so sorry,  I made a mistake.
The links work well.
